### ISSUE TITLE
No game folder

### ISSUE THREAD

**Issue by Nabbit-Gamer** [mayday-mayjay/MJ-MAS-submod-multiname#1]
I used 7Zip to extract the folder, but there _wasn't_ a game folder in the new extracted folder. The instructions for installation mention a game folder but I _couldn't find one_. I thought "_well, I can just create my own game folder and put the stuff in there and then put it in MAS and it'll probably work_". Spoiler Alert: It didn't. (_Specifically, the game had an error on launch, and it said the issue was that I downloaded the submod twice_) So then I thought "_well, it's a submod, so I probably need to also create a submod folder inside the game folder and then put all the files in there!_" So I undid the changes, created a submod folder inside the game folder, and then put it back in, and ran into the same problem. So I decide to create this... post, I guess? I'm not sure what to call it, so let's just go with post.

**Comment by AzhamProdLive** [comment]
Fixed, redownload the release : https://github.com/mayday-mayjay/MJ-MAS-submod-multiname/releases/tag/1.0.0
